server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:springbatchchunk
  jpa:
    show-sql: true
  batch:
    job:
      enabled: false
#    jdbc:
#      schema: classpath:org/springframework/batch/core/schema-mysql.sql
#      initialize-schema: always