server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:springbatchtasklet
  jpa:
    show-sql: true
  batch:
    job:
      enabled: false